# Generated by Django 3.2.4 on 2021-07-01 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
